### ISSUE TITLE
Can you give an estimate to how long it'll take until this corpus is published?

### ISSUE THREAD

**Issue by LBlend** [ltgoslo/norec_gender#1]
I am currently working on a project that could greatly benefit from this corpus. I was thinking about manually tagging the [NAK (Norsk Aviskorpus)](https://www.nb.no/sprakbanken/ressurskatalog/oai-nb-no-sbr-4/) corpus myself, but after seeing that you're working on tagging a large norwegian dataset by gender I feel kind of conflicted.

I would appreciate it if you could give an estimate to how long it'll take to finish tagging the corpus and publishing for the public.

**Comment by SamiaTouileb** [comment]
Sorry for the very late reply. The dataset and metadata is now available.

**Comment by LBlend** [comment]
No worries! Thank you!
